services:
  cache:
    image: caching-proxies-cache:latest
    container_name: caching-proxies-cache-testnet
    pull_policy: never
    command:
      - "./app/app"
      - "-shard-prefix=shards"
      - "-shards-to-listen=1,2,3,4"
      - "-creds=config/caching.creds"
      - "-server=nats://rpc-speedup-nats.testnet.aurora.dev"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    ports:
      - "1324:1324"